apply and destroy separate jobs created

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,8 +46,7 @@ jobs:
         run: checkov -d . --framework terraform --soft-fail
         working-directory: ./
 
-  terraform_apply:
-    if: ${{ github.event.inputs.action == 'apply' }}
+  terraform_apply_destroy:
     name: Terraform Deployment
     runs-on: ubuntu-latest
     needs: lint-and-security
@@ -79,43 +78,15 @@ jobs:
         run: terraform plan -var-file="terraform.tfvars" -lock=false
         working-directory: ./
 
-      - name: Apply Terraform
-        run: terraform apply -var-file="terraform.tfvars" -auto-approve -lock=false
-        working-directory: ./
-        
-  terraform_destroy:
-      if: ${{ github.event.inputs.action == 'destroy' }}
-      name: Terraform Deployment
-      runs-on: ubuntu-latest
-      needs: lint-and-security
-  
-      steps:
-        - name: Checkout code
-          uses: actions/checkout@v4
-  
-        - name: Configure AWS Credentials
-          uses: aws-actions/configure-aws-credentials@v4
-          with:
-            role-to-assume: arn:aws:iam::211125325699:role/Demo_Access
-            aws-region: us-east-1
-  
-        - name: Set up Terraform
-          uses: hashicorp/setup-terraform@v2.0.3
-          with:
-            terraform_version: ">= 1.12.0"
-  
-        - name: Initialize Terraform
-          run: terraform init
-          working-directory: ./
-  
-        - name: Validate Terraform
-          run: terraform validate
-          working-directory: ./
-  
-        - name: Generate Terraform Plan
-          run: terraform plan -var-file="terraform.tfvars" -lock=false
-          working-directory: ./
-  
-        - name: Apply Terraform
-          run: terraform destroy -var-file="terraform.tfvars" -auto-approve -lock=false
-          working-directory: ./ 
+      - name: Perform Action
+        run: |
+          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
+            terraform apply -auto-approve
+          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
+            terraform destroy -auto-approve
+          else
+            echo "Invalid action selected."
+            exit 1
+          fi
+
+ 
